In [779]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
%matplotlib inline
sns.set(style="whitegrid", palette="muted")
df = pd.read_csv('train.csv')
df.info()
test = pd.read_csv('test.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-n

In [639]:
df = pd.concat([df,test],ignore_index= True)

#df[1458:][['Id','SalePrice']]
#sns.swarmplot(x= 'GrLivArea', y = 'SalePrice', data = df, hue = 'LandContour')  v        

In [640]:
#sns.swarmplot(x= 'SalePrice', y = 'SalePrice', data = df, hue='LotConfig')
#plt.tight_layout()

In [780]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-n

In [781]:
df[['WoodDeckSF','OpenPorchSF','EnclosedPorch','3SsnPorch','ScreenPorch']]

WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch
0              0           61              0          0            0
1            298            0              0          0            0
2              0           42              0          0            0
3              0           35            272          0            0
4            192           84              0          0            0
5             40           30              0        320            0
6            255           57              0          0            0
7            235          204            228          0            0
8             90            0            205          0            0
9              0            4              0          0            0
10             0            0              0          0            0
11           147           21              0          0            0
12           140            0              0          0          176
13           160           33              0          0            0
14             0          213            176          0            0
15            48          112              0          0            0
16             0            0              0          0            0
17             0            0              0          0            0
18             0          102              0          0            0
19             0            0              0          0            0
20           240          154              0          0            0
21             0            0            205          0            0
22           171          159              0          0            0
23           100          110              0          0            0
24           406           90              0          0            0
25             0           56              0          0            0
26           222           32              0          0            0
27             0           50              0          0            0
28           288          258              0          0            0
29            49            0             87          0            0
...          ...          ...            ...        ...          ...
1430         100           40              0          0            0
1431           0           60              0          0            0
1432           0            0              0          0            0
1433           0            0              0          0            0
1434         295           41              0          0            0
1435           0           36              0          0            0
1436           0            0              0          0            0
1437           0           66              0        304            0
1438           0          158            158          0            0
1439           0           88            216          0            0
1440         431            0              0          0            0
1441         149            0              0          0            0
1442         168           52              0          0            0
1443           0           98              0          0           40
1444         192           60              0          0            0
1445           0            0            252          0            0
1446         261           39              0          0            0
1447           0           65              0          0            0
1448         168           24              0          0            0
1449           0            0              0          0            0
1450          32           45              0          0            0
1451           0           36              0          0            0
1452           0           28              0          0            0
1453          36           56              0          0            0
1454           0          113              0          0            0
1455           0           40              0          0            0
1456

In [782]:
df.loc[df['SaleType'].isnull(),('SaleType','SaleCondition')]
df['SaleType'].mode()[0]

'WD'

In [783]:
df.loc[df['TotalBsmtSF'].isnull(),('TotalBsmtSF','BsmtFinType1','BsmtFinType2')]
df.loc[df['TotalBsmtSF'].isnull(),('TotalBsmtSF')]=0
df['MSZoning'] = df['MSZoning'].fillna(df['MSZoning'].mode()[0])
df['KitchenQual'] = df['KitchenQual'].fillna(df['KitchenQual'].mode()[0])
df['Utilities'] = df['Utilities'].fillna(df['Utilities'].mode()[0])
df['SaleType'] = df['SaleType'].fillna(df['SaleType'].mode()[0])
df['MSZoning'] = df['MSZoning'].fillna(df['MSZoning'].mode()[0])
df['Utilities'] = df['Utilities'].fillna(df['Utilities'].mode()[0])
df.loc[df['GarageCars'].isnull(),('GarageCars','GarageArea','GarageQual')]
df.loc[df['GarageCars'].isnull(),('GarageCars','GarageArea')] =0
df['Exterior1st'] = df['Exterior1st'].fillna(df['Exterior1st'].mode()[0])
df['Exterior2nd'] = df['Exterior2nd'].fillna(df['Exterior2nd'].mode()[0])
df['Functional'] = df['Functional'].fillna(df['Functional'].mode()[0])
df.loc[df['BsmtUnfSF'].isnull(),('BsmtUnfSF', 'BsmtFinType2')]
df.loc[df['BsmtUnfSF'].isnull(),('BsmtUnfSF')] =0
df.loc[df['BsmtFinSF1'].isnull(),('BsmtFinSF1')] =0
df.loc[df['BsmtFinSF2'].isnull(),('BsmtFinSF2')] =0
df.loc[df['BsmtFullBath'].isnull(),('BsmtFullBath')] =df['BsmtFullBath'].mode()[0]
df.loc[df['BsmtHalfBath'].isnull(),('BsmtHalfBath')] = df['BsmtHalfBath'].mode()[0]

In [784]:
LandSlope_dict = {'Sev':0,'Mod':1, 'Gtl':2}
print(df['LandSlope'].unique())
df['LandSlope'] = df['LandSlope'].map(LandSlope_dict)
df['LandSlope'].unique()

['Gtl' 'Mod' 'Sev']


array([2, 1, 0], dtype=int64)

In [785]:
Functional_dict = {'Sal':0,'Sev':1, 'Maj2':2,'Maj1':3,'Mod':4,'Min2':5,'Min1':6,'Typ':7}
print(df['Functional'].unique())
df['Functional'] = df['Functional'].map(Functional_dict)
df['Functional'].unique()

['Typ' 'Min1' 'Maj1' 'Min2' 'Mod' 'Maj2' 'Sev']


array([7, 6, 3, 5, 4, 2, 1], dtype=int64)

In [786]:

PavedDrive_dict = {'N':0,'P':1, 'Y':2}
print(df['PavedDrive'].unique())
df['PavedDrive'] = df['PavedDrive'].map(PavedDrive_dict)
df['PavedDrive'].unique()

['Y' 'N' 'P']


array([2, 0, 1], dtype=int64)

In [787]:
Street_dict = {'Grvl':0,'Pave':1}
print(df['Street'].unique())
df['Street'] = df['Street'].map(Street_dict)
df['Street'].unique()

['Pave' 'Grvl']


array([1, 0], dtype=int64)

In [788]:
df.loc[(df['Condition1']==df['Condition2'])&(df['Condition2']!='Norm'), 'Condition2'] = 'Norm'

In [789]:
df['LocationProximity'] = df.apply(lambda x: 2 if x['Condition1']!='Norm' and x['Condition2']!='Norm' else 1 if x['Condition1']!='Norm' and x['Condition2']=='Norm' else 0, axis =1) 

In [790]:

df['isNew'] = df['SaleType'].apply(lambda x:1 if x=='New' else 0)

In [791]:

#sns.categorical.swarmplot(x= 'Functional', y = 'SalePrice', data = df)
#sns.swarmplot(x= 'GrLivArea', y = 'SalePrice', data = df, hue = 'Functional')
LotShape_dict = {'IR3':0,'IR2':1,'IR1':2, 'Reg':3}
print(df['LotShape'].unique())
df['LotShape'] = df['LotShape'].map(LotShape_dict)
df['LotShape'].unique()

['Reg' 'IR1' 'IR2' 'IR3']


array([3, 2, 1, 0], dtype=int64)

In [792]:
print(df['Utilities'].unique())
Utilities_dict ={'ELO':0,'NoSeWa':1,'NoSewr':2, 'AllPub':3}
df['Utilities'] = df['Utilities'].map(Utilities_dict)
df['Utilities'].unique()

['AllPub' 'NoSeWa']


array([3, 1], dtype=int64)

In [793]:
#sns.swarmplot(x='GrLivArea', y = 'SalePrice', data = df)
#plt.scatter(x='GrLivArea', y = 'SalePrice', data = df)
df.drop(df[(df['GrLivArea']>4000)& (df['SalePrice']<300000)].index, axis =0, inplace=True)

In [794]:
df.drop('PoolArea', axis = 1, inplace=True)

In [795]:
#removing the misleading value of area 1
df.loc[(df['MasVnrType']=='None') & (df['MasVnrArea']==1),'MasVnrArea']=0

In [796]:
#where area and type both are null, setting them to 0 and none respectively
print(df.loc[(df['MasVnrType'].isnull()) & (df['MasVnrArea'].isnull()),('MasVnrArea','MasVnrType')])
df.loc[(df['MasVnrType'].isnull()) & (df['MasVnrArea'].isnull()),('MasVnrArea','MasVnrType')]=0,'None'
df.loc[(df['MasVnrType'].isnull()) & (df['MasVnrArea'].isnull()),('MasVnrArea','MasVnrType')]

      MasVnrArea MasVnrType
234          NaN        NaN
529          NaN        NaN
650          NaN        NaN
936          NaN        NaN
973          NaN        NaN
977          NaN        NaN
1243         NaN        NaN
1278         NaN        NaN


Empty DataFrame
Columns: [MasVnrArea, MasVnrType]
Index: []

In [797]:
#when area is 0 bt Type is not none, setting type to the mean of area
df.loc[(df['MasVnrType']!='None') & (df['MasVnrArea']==0),('MasVnrArea')]=df[df['MasVnrArea']!=0]['MasVnrArea'].mean()

In [798]:
#when area is not 0 bt Type is none, setting type to the mode of types
print(df.loc[(df['MasVnrType']=='None') & (df['MasVnrArea']!=0),('MasVnrType','MasVnrArea')])
df.loc[(df['MasVnrType']=='None') & (df['MasVnrArea']!=0),('MasVnrType')]=df[df['MasVnrType']!='None']['MasVnrType'].mode().iloc[0]
df.loc[(df['MasVnrType']=='None') & (df['MasVnrArea']!=0),('MasVnrType','MasVnrArea')]

     MasVnrType  MasVnrArea
624        None       288.0
1300       None       344.0
1334       None       312.0


Empty DataFrame
Columns: [MasVnrType, MasVnrArea]
Index: []

In [799]:
print(df[df['MasVnrType']=='None'].count()['Id'])
print(df[df['MasVnrType'].isnull()].count()['Id'])
print(df[df['MasVnrArea']==0].count()['Id'])
print(df[df['MasVnrArea'].isnull()].count()['Id'])

869
0
869
0


In [800]:
#where type is null bt area is greater than 0 setting it to mode of types
print(df.loc[(df['MasVnrType'].isnull()) & (df['MasVnrArea']!=0),'MasVnrType'])
df.loc[(df['MasVnrType'].isnull()) & (df['MasVnrArea']!=0),'MasVnrType']=df[df['MasVnrType']!='None']['MasVnrType'].mode()[0]
df.loc[(df['MasVnrType'].isnull()) & (df['MasVnrArea']!=0),'MasVnrType']

Series([], Name: MasVnrType, dtype: object)


Series([], Name: MasVnrType, dtype: object)

In [801]:
print(df['Alley'].unique())
df['Alley']=df['Alley'].fillna('NA')
df['Alley'].unique()

[nan 'Grvl' 'Pave']


array(['NA', 'Grvl', 'Pave'], dtype=object)

In [802]:
Alley_dict = {'Grvl':1,'Pave':2, 'NA':0}
print(df['Alley'].unique())
df['Alley'] = df['Alley'].map(Alley_dict)
df['Alley'].unique()

['NA' 'Grvl' 'Pave']


array([0, 1, 2], dtype=int64)

In [803]:
print(df['LotFrontage'].unique())
df['LotFrontage']=df['LotFrontage'].fillna(0)
df['LotFrontage'].unique()

[  65.   80.   68.   60.   84.   85.   75.   nan   51.   50.   70.   91.
   72.   66.  101.   57.   44.  110.   98.   47.  108.  112.   74.  115.
   61.   48.   33.   52.  100.   24.   89.   63.   76.   81.   95.   69.
   21.   32.   78.  121.  122.   40.  105.   73.   77.   64.   94.   34.
   90.   55.   88.   82.   71.  120.  107.   92.  134.   62.   86.  141.
   97.   54.   41.   79.  174.   99.   67.   83.   43.  103.   93.   30.
  129.  140.   35.   37.  118.   87.  116.  150.  111.   49.   96.   59.
   36.   56.  102.   58.   38.  109.  130.   53.  137.   45.  106.  104.
   42.   39.  144.  114.  128.  149.  313.  168.  182.  138.  160.  152.
  124.  153.   46.]


array([  65.,   80.,   68.,   60.,   84.,   85.,   75.,    0.,   51.,
         50.,   70.,   91.,   72.,   66.,  101.,   57.,   44.,  110.,
         98.,   47.,  108.,  112.,   74.,  115.,   61.,   48.,   33.,
         52.,  100.,   24.,   89.,   63.,   76.,   81.,   95.,   69.,
         21.,   32.,   78.,  121.,  122.,   40.,  105.,   73.,   77.,
         64.,   94.,   34.,   90.,   55.,   88.,   82.,   71.,  120.,
        107.,   92.,  134.,   62.,   86.,  141.,   97.,   54.,   41.,
         79.,  174.,   99.,   67.,   83.,   43.,  103.,   93.,   30.,
        129.,  140.,   35.,   37.,  118.,   87.,  116.,  150.,  111.,
         49.,   96.,   59.,   36.,   56.,  102.,   58.,   38.,  109.,
        130.,   53.,  137.,   45.,  106.,  104.,   42.,   39.,  144.,
        114.,  128.,  149.,  313.,  168.,  182.,  138.,  160.,  152.,
        124.,  153.,   46.])

In [804]:
print(df['BsmtQual'].unique())
df['BsmtQual']=df['BsmtQual'].fillna('NA')
df['BsmtQual'].unique()

['Gd' 'TA' 'Ex' nan 'Fa']


array(['Gd', 'TA', 'Ex', 'NA', 'Fa'], dtype=object)

In [805]:
print(df['BsmtCond'].unique())
df['BsmtCond']=df['BsmtCond'].fillna('NA')
df['BsmtCond'].unique()

['TA' 'Gd' nan 'Fa' 'Po']


array(['TA', 'Gd', 'NA', 'Fa', 'Po'], dtype=object)

In [806]:
print(df['BsmtExposure'].unique())
df['BsmtExposure']=df['BsmtExposure'].fillna('NA')
df['BsmtExposure'].unique()

['No' 'Gd' 'Mn' 'Av' nan]


array(['No', 'Gd', 'Mn', 'Av', 'NA'], dtype=object)

In [807]:
print(df['BsmtFinType1'].unique())
df['BsmtFinType1']=df['BsmtFinType1'].fillna('NA')
df['BsmtFinType1'].unique()

['GLQ' 'ALQ' 'Unf' 'Rec' 'BLQ' nan 'LwQ']


array(['GLQ', 'ALQ', 'Unf', 'Rec', 'BLQ', 'NA', 'LwQ'], dtype=object)

In [808]:
BsmtFinType_dict ={'NA':0,'Unf':1,'LwQ':2, 'Rec':3, 'BLQ':4, 'ALQ':5, 'GLQ':6}
print(df['BsmtFinType1'].unique())
df['BsmtFinType1'] = df['BsmtFinType1'].map(BsmtFinType_dict)
df['BsmtFinType1'].unique()

['GLQ' 'ALQ' 'Unf' 'Rec' 'BLQ' 'NA' 'LwQ']


array([6, 5, 1, 3, 4, 0, 2], dtype=int64)

In [809]:
print(df['BsmtFinType2'].unique())
df['BsmtFinType2']=df['BsmtFinType2'].fillna('NA')
df['BsmtFinType2'].unique()

['Unf' 'BLQ' nan 'ALQ' 'Rec' 'LwQ' 'GLQ']


array(['Unf', 'BLQ', 'NA', 'ALQ', 'Rec', 'LwQ', 'GLQ'], dtype=object)

In [810]:
print(df['BsmtFinType2'].unique())
df['BsmtFinType2'] = df['BsmtFinType2'].map(BsmtFinType_dict)
df['BsmtFinType2'].unique()

['Unf' 'BLQ' 'NA' 'ALQ' 'Rec' 'LwQ' 'GLQ']


array([1, 4, 0, 5, 3, 2, 6], dtype=int64)

In [811]:
df['Electrical'].mode().iloc[0]
df['Electrical']=df['Electrical'].fillna(df['Electrical'].mode().iloc[0])

In [812]:
Electrical_dict = {'Mix':0,'FuseP':1, 'FuseF':2,'FuseA':3,'SBrkr':4}
print(df['Electrical'].unique())
df['Electrical'] = df['Electrical'].map(Electrical_dict)
df['Electrical'].unique()

['SBrkr' 'FuseF' 'FuseA' 'FuseP' 'Mix']


array([4, 2, 3, 1, 0], dtype=int64)

In [813]:
print(df['FireplaceQu'].unique())
df['FireplaceQu']=df['FireplaceQu'].fillna('NA')
df['FireplaceQu'].unique()

[nan 'TA' 'Gd' 'Fa' 'Ex' 'Po']


array(['NA', 'TA', 'Gd', 'Fa', 'Ex', 'Po'], dtype=object)

In [814]:
print(df['GarageType'].unique())
df['GarageType']=df['GarageType'].fillna('NA')
df['GarageType'].unique()

['Attchd' 'Detchd' 'BuiltIn' 'CarPort' nan 'Basment' '2Types']


array(['Attchd', 'Detchd', 'BuiltIn', 'CarPort', 'NA', 'Basment', '2Types'], dtype=object)

In [815]:
#where GarageYrBlt is missing, set it as YearRemodAdd
print(df['GarageYrBlt'].unique())
#df['GarageYrBlt']=df['GarageYrBlt'].fillna(df['YearRemodAdd'])
df.loc[(df['GarageYrBlt'].isnull()) & (df['GarageType']!='NA'),'GarageYrBlt']=df['YearRemodAdd']
df.loc[(df['GarageYrBlt'].isnull()) & (df['GarageType']=='NA'),'GarageYrBlt']=0
#df['GarageYrBlt'].unique()
df[['YearBuilt','GarageYrBlt','YearRemodAdd']]
df['GarageYrBlt'].unique()

[ 2003.  1976.  2001.  1998.  2000.  1993.  2004.  1973.  1931.  1939.
  1965.  2005.  1962.  2006.  1960.  1991.  1970.  1967.  1958.  1930.
  2002.  1968.  2007.  2008.  1957.  1920.  1966.  1959.  1995.  1954.
  1953.    nan  1983.  1977.  1997.  1985.  1963.  1981.  1964.  1999.
  1935.  1990.  1945.  1987.  1989.  1915.  1956.  1948.  1974.  2009.
  1950.  1961.  1921.  1900.  1979.  1951.  1969.  1936.  1975.  1971.
  1923.  1984.  1926.  1955.  1986.  1988.  1916.  1932.  1972.  1918.
  1980.  1924.  1996.  1940.  1949.  1994.  1910.  1978.  1982.  1992.
  1925.  1941.  2010.  1927.  1947.  1937.  1942.  1938.  1952.  1928.
  1922.  1934.  1906.  1914.  1946.  1908.  1929.  1933.]


array([ 2003.,  1976.,  2001.,  1998.,  2000.,  1993.,  2004.,  1973.,
        1931.,  1939.,  1965.,  2005.,  1962.,  2006.,  1960.,  1991.,
        1970.,  1967.,  1958.,  1930.,  2002.,  1968.,  2007.,  2008.,
        1957.,  1920.,  1966.,  1959.,  1995.,  1954.,  1953.,     0.,
        1983.,  1977.,  1997.,  1985.,  1963.,  1981.,  1964.,  1999.,
        1935.,  1990.,  1945.,  1987.,  1989.,  1915.,  1956.,  1948.,
        1974.,  2009.,  1950.,  1961.,  1921.,  1900.,  1979.,  1951.,
        1969.,  1936.,  1975.,  1971.,  1923.,  1984.,  1926.,  1955.,
        1986.,  1988.,  1916.,  1932.,  1972.,  1918.,  1980.,  1924.,
        1996.,  1940.,  1949.,  1994.,  1910.,  1978.,  1982.,  1992.,
        1925.,  1941.,  2010.,  1927.,  1947.,  1937.,  1942.,  1938.,
        1952.,  1928.,  1922.,  1934.,  1906.,  1914.,  1946.,  1908.,
        1929.,  1933.])

In [816]:
print(df['GarageFinish'].unique())
df['GarageFinish']=df['GarageFinish'].fillna('NA')
df['GarageFinish'].unique()

['RFn' 'Unf' 'Fin' nan]


array(['RFn', 'Unf', 'Fin', 'NA'], dtype=object)

In [817]:
GarageFinish_dict ={'NA':0,'Unf':1,'RFn':2, 'Fin':3}
print(df['GarageFinish'].unique())
df['GarageFinish'] = df['GarageFinish'].map(GarageFinish_dict)
df['GarageFinish'].unique()

['RFn' 'Unf' 'Fin' 'NA']


array([2, 1, 3, 0], dtype=int64)

In [818]:
print(df['GarageQual'].unique())
df['GarageQual']=df['GarageQual'].fillna('NA')
df['GarageQual'].unique()

['TA' 'Fa' 'Gd' nan 'Ex' 'Po']


array(['TA', 'Fa', 'Gd', 'NA', 'Ex', 'Po'], dtype=object)

In [819]:
print(df['GarageCond'].unique())
df['GarageCond']=df['GarageCond'].fillna('NA')
df['GarageCond'].unique()

['TA' 'Fa' nan 'Gd' 'Po' 'Ex']


array(['TA', 'Fa', 'NA', 'Gd', 'Po', 'Ex'], dtype=object)

In [820]:

print(df['PoolQC'].unique())
df['PoolQC']=df['PoolQC'].fillna('NA')
df['PoolQC'].unique()

[nan 'Ex' 'Fa' 'Gd']


array(['NA', 'Ex', 'Fa', 'Gd'], dtype=object)

In [821]:
print(df['Fence'].unique())
df['Fence']=df['Fence'].fillna('NA')
df['Fence'].unique()

[nan 'MnPrv' 'GdWo' 'GdPrv' 'MnWw']


array(['NA', 'MnPrv', 'GdWo', 'GdPrv', 'MnWw'], dtype=object)

In [822]:
Fence_dict ={'NA':0,'MnWw':1,'GdWo':2, 'MnPrv':3, 'GdPrv':4}
print(df['Fence'].unique())
df['Fence'] = df['Fence'].map(Fence_dict)
df['Fence'].unique()

['NA' 'MnPrv' 'GdWo' 'GdPrv' 'MnWw']


array([0, 3, 2, 4, 1], dtype=int64)

In [823]:
print(df['MiscFeature'].unique())
df['MiscFeature']=df['MiscFeature'].fillna('NA')
df['MiscFeature'].unique()

[nan 'Shed' 'Gar2' 'Othr' 'TenC']


array(['NA', 'Shed', 'Gar2', 'Othr', 'TenC'], dtype=object)

In [824]:

df['CentralAir_0']=df.apply(lambda x: 1 if x['CentralAir']=='Yes' else 0, axis =1)
df.drop('CentralAir', axis =1 , inplace=True)

In [825]:
df['Garage'] = df.apply(lambda x: np.log(x['GarageCars']*x['GarageArea']+1), axis=1)
df.head()[['Garage','GarageCars','GarageArea']]

Garage  GarageCars  GarageArea
0  7.000334           2         548
1  6.825460           2         460
2  7.104144           2         608
3  7.563720           3         642
4  7.827640           3         836

In [826]:
df['isRemodAdd']=df.apply(lambda x: x['YearRemodAdd']>x['YearBuilt'], axis =1)
#sns.lmplot(x='YearBuilt',y='SalePrice',data=df, hue = 'isRemodAdd',scatter_kws={'alpha':0.25})
df['yrsOld'] = df.apply(lambda x: x['YrSold']-x['YearBuilt'], axis =1)
#sns.lmplot(x='yrsOld',y='SalePrice',data=df, hue = 'isRemodAdd',scatter_kws={'alpha':0.25})
df['RemodAddNumYrs'] = df.apply(lambda x: x['YrSold']-x['YearRemodAdd'], axis =1)
print(df['BsmtFinType1'].head())
df['numOfBsmt']= df.apply(lambda x: 1 if x['BsmtFinType1']!=0 and x['BsmtFinType2']==0 else 2 if x['BsmtFinType1']!=0 and x['BsmtFinType2']!=0 else 0, axis = 1)
df['TotalFinBsmtSF']=df.apply(lambda x: x['BsmtFinSF2']+x['BsmtFinSF1'], axis =1)
df['TotalBathsAbvGrnd']=df.apply(lambda x: x['FullBath']+(x['HalfBath']/2), axis =1)
df['TotalBathsBsmt']=df.apply(lambda x: x['BsmtFullBath']+(x['BsmtHalfBath']/2), axis =1)
df['GarageYrsOld']=df.apply(lambda x: x['YrSold']-x['GarageYrBlt'], axis =1)
df['TotalPorchArea']=df.apply(lambda x: x['WoodDeckSF']+x['OpenPorchSF']+x['EnclosedPorch']+x['3SsnPorch']+x['ScreenPorch'], axis =1)
'Gd', 'TA', 'Ex', 'Fa'
z = {'Ex': 5, 'Gd': 4, 'TA': 3, 'Fa':2, 'Po':1, 'NA': 0}
z2 = {'Gd': 3, 'Av':2, 'Mn':1, 'NA': -1, 'No':0}
z.keys()
df['HeatingQuality']= df['HeatingQC'].map(z)

df['ExterQuality'] = df['ExterQual'].map(z)

df['KitchenQuality'] = df['KitchenQual'].map(z)
#df['FireplaceQuality'] = df['FireplaceQu'].map(z)

#df['GarageQuality'] = df['GarageQual'].map(z)

#df['GarageCondition'] = df['GarageCond'].map(z)
df['PoolQuality'] = df['PoolQC'].map(z)
df['BsmtCondition'] = df['BsmtCond'].map(z)
df['BsmtQual'] = df['BsmtQual'].map(z)
#df['GarageCondition'] = df['GarageCond'].map(z)
df['BsmtExposureMapped'] = df['BsmtExposure'].map(z2)
#df['BsmtExposure'].unique()
#df['ExterCondition'] = df['ExterCond'].map(z)
#df.drop('OverallQualcond', axis = 1, inplace=True)
#df['OverallQualcond']=df.apply(lambda x: (x['OverallQual']+x['OverallCond'])/2, axis =1)
#df['NumOfFloors']=df.apply(lambda x: 1 if x['2ndFlrSF']==0 else 2, axis =1)
#df[(df['BsmtFinType1']=='NA') &((df['BsmtFinType2']!='NA'))]
#df[df['numOfBsmt']!=2][['numOfBsmt','BsmtFinType1','BsmtFinType2']]
#plt.scatter()

0    6
1    5
2    6
3    5
4    6
Name: BsmtFinType1, dtype: int64


In [827]:
df['GarageCondition'] = df['GarageCond'].map(z)
df.drop(['GarageCond'],axis = 1, inplace=True)

In [828]:
df.drop(['BsmtExposure'],axis = 1, inplace=True)
#df.drop(['KitchenQual','HeatingQC','ExterQual'],axis = 1, inplace=True)
#df.drop(['FireplaceQu','GarageQual'],axis = 1, inplace=True)
#df.drop(['GarageCond'],axis = 1, inplace=True)
#df.drop(['PoolQC'],axis = 1, inplace=True)
#df.drop(['ExterCond'],axis = 1, inplace=True)
#df.drop(['ExterCond'],axis = 1, inplace=True)
#df.drop(['BsmtCondition'],axis = 1, inplace=True)
df.drop(['MiscVal'],axis = 1, inplace=True)


In [829]:
SalePrice = df[['Id','SalePrice']]
SalePrice[['Id','SalePrice']].iloc[0]
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2',
       'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'Electrical',
       '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath',
       'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr',
       'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces',
       'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish',
       'GarageCars', 'GarageArea', 'GarageQual', 'PavedDrive', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPor

In [830]:
df['BsmtCondition'].dtype

dtype('int64')

In [831]:
#column_types = list()
#for x in df.columns:
#    column_types.append((x,type(df[x].iloc[0])))
column_types=[(x,type(df[x].iloc[0])) for x in df.columns]
cat_columns = [x for (x,coltype) in column_types if coltype==str]
numerical_columns = df.columns.difference(cat_columns)
date_columns = ['YearRemodAdd', 'YrSold' , 'YearBuilt', 'MoSold', 'GarageYrBlt']
len(df.columns) - (len(cat_columns)+len(numerical_columns))
numerical_columns = numerical_columns.difference(['MSSubClass'])
cat_columns = cat_columns.append('MSSubClass')
numerical_columns.difference(date_columns)
print(['Id','SalePrice'].append(date_columns))
cols_normalize = numerical_columns.difference(date_columns)
cols_normalize

None


Index(['1stFlrSF', '2ndFlrSF', '3SsnPorch', 'Alley', 'BedroomAbvGr',
       'BsmtCondition', 'BsmtExposureMapped', 'BsmtFinSF1', 'BsmtFinSF2',
       'BsmtFinType1', 'BsmtFinType2', 'BsmtFullBath', 'BsmtHalfBath',
       'BsmtQual', 'BsmtUnfSF', 'CentralAir_0', 'Electrical', 'EnclosedPorch',
       'ExterQuality', 'Fence', 'Fireplaces', 'FullBath', 'Functional',
       'Garage', 'GarageArea', 'GarageCars', 'GarageCondition', 'GarageFinish',
       'GarageYrsOld', 'GrLivArea', 'HalfBath', 'HeatingQuality', 'Id',
       'KitchenAbvGr', 'KitchenQuality', 'LandSlope', 'LocationProximity',
       'LotArea', 'LotFrontage', 'LotShape', 'LowQualFinSF', 'MasVnrArea',
       'OpenPorchSF', 'OverallCond', 'OverallQual', 'PavedDrive',
       'PoolQuality', 'RemodAddNumYrs', 'SalePrice', 'ScreenPorch', 'Street',
       'TotRmsAbvGrd', 'TotalBathsAbvGrnd', 'TotalBathsBsmt', 'TotalBsmtSF',
       'TotalFinBsmtSF', 'TotalPorchArea', 'Utilities', 'WoodDeckSF', 'isNew',
       'isRemodAdd', 'numOfBsmt',

In [832]:
from sklearn.preprocessing import StandardScaler
scaler  = StandardScaler()
scaler.fit(df[cols_normalize].drop(['Id','SalePrice'], axis =1))
dff_n = df.copy()
#dff_n[cols_normalize.difference(['Id','SalePrice'])] = pd.DataFrame(scaler.transform(df[cols_normalize].drop(['Id','SalePrice'], axis =1)), columns= cols_normalize.difference(['Id','SalePrice']))
dff_n[cols_normalize.difference(['Id','SalePrice'])] = scaler.transform(df[cols_normalize].drop(['Id','SalePrice'], axis =1))
#dff_n[cols_normalize.difference(['Id','SalePrice'])] =scaler.transform(df[cols_normalize].drop(['Id','SalePrice'], axis =1))
#dff_n = pd.concat(dff_n.append(SalePrice)
#dff_n[['Id','SalePrice']].merge(SalePrice)
dff_n[['Id','SalePrice']] = SalePrice
dff_n.head()



Id  MSSubClass MSZoning  LotFrontage   LotArea    Street     Alley  \
0   1          60       RL     0.223761 -0.203934  0.064282 -0.243202   
1   2          20       RL     0.665308 -0.087252  0.064282 -0.243202   
2   3          60       RL     0.312070  0.080162  0.064282 -0.243202   
3   4          70       RL     0.076579 -0.092325  0.064282 -0.243202   
4   5          60       RL     0.783053  0.385566  0.064282 -0.243202   

   LotShape LandContour  Utilities       ...        TotalBathsBsmt  \
0  0.702100         Lvl   0.026198       ...              1.066169   
1  0.702100         Lvl   0.026198       ...              0.092188   
2 -1.027059         Lvl   0.026198       ...              1.066169   
3 -1.027059         Lvl   0.026198       ...              1.066169   
4 -1.027059         Lvl   0.026198       ...              1.066169   

   GarageYrsOld TotalPorchArea HeatingQuality ExterQuality KitchenQuality  \
0     -0.295846      -0.767682       0.892277     1.061109       0.741127   
1     -0.238557       0.750894       0.892277    -0.689001      -0.770150   
2     -0.291439      -0.889424       0.892277     1.061109       0.741127   
3     -0.289236       0.808561      -0.150143    -0.689001       0.741127   
4     -0.289236       0.609929       0.892277     1.061109       0.741127   

  PoolQuality  BsmtCondition  BsmtExposureMapped  GarageCondition  
0   -0.060845       0.117966           -0.589102         0.265813  
1   -0.060845       0.117966            2.230080         0.265813  
2   -0.060845       0.117966            0.350625         0.265813  
3   -0.060845       1.928437           -0.589102         0.265813  
4   -0.060845       0.117966            1.290352         0.265813  

[5 rows x 96 columns]

In [833]:
dff_n.drop(['numOfBsmt','BsmtUnfSF', 'HalfBath', 'FullBath', 'BsmtFullBath', 'BsmtHalfBath'],axis=1, inplace=True)

In [834]:
dff=pd.get_dummies(dff_n.drop(['BsmtCond'],axis=1))

#new=pd.get_dummies(dff['MSSubClass'], prefix='MSSubClass')
#dff=pd.concat([dff,new], axis =1)
#dff.drop('MSSubClass', axis = 1, inplace=True)
#dff=dff.copy()

In [835]:
dff = pd.concat([dff,pd.get_dummies(dff['MSSubClass'], prefix='MSSubClass')], axis=1)
dff.index.values
dff.drop('MSSubClass', axis = 1, inplace=True)
dff.head()

Id  LotFrontage   LotArea    Street     Alley  LotShape  Utilities  \
0   1     0.223761 -0.203934  0.064282 -0.243202  0.702100   0.026198   
1   2     0.665308 -0.087252  0.064282 -0.243202  0.702100   0.026198   
2   3     0.312070  0.080162  0.064282 -0.243202 -1.027059   0.026198   
3   4     0.076579 -0.092325  0.064282 -0.243202 -1.027059   0.026198   
4   5     0.783053  0.385566  0.064282 -0.243202 -1.027059   0.026198   

   LandSlope  OverallQual  OverallCond       ...        MSSubClass_60  \
0   0.225879     0.658506    -0.517649       ...                    1   
1   0.225879    -0.068293     2.177825       ...                    0   
2   0.225879     0.658506    -0.517649       ...                    1   
3   0.225879     0.658506    -0.517649       ...                    0   
4   0.225879     1.385305    -0.517649       ...                    1   

   MSSubClass_70  MSSubClass_75  MSSubClass_80  MSSubClass_85  MSSubClass_90  \
0              0              0              0              0              0   
1              0              0              0              0              0   
2              0              0              0              0              0   
3              1              0              0              0              0   
4              0              0              0              0              0   

   MSSubClass_120  MSSubClass_160  MSSubClass_180  MSSubClass_190  
0               0               0               0               0  
1               0               0               0               0  
2               0               0               0               0  
3               0               0               0               0  
4               0               0               0               0  

[5 rows x 265 columns]

In [836]:
dff_train = dff[:1458].drop(['GarageCars','GarageArea', 'SalePrice','YearRemodAdd','YearBuilt', 'WoodDeckSF','OpenPorchSF','EnclosedPorch','3SsnPorch','ScreenPorch'], axis =1)
dff_train_y = dff[:1458]['SalePrice']
dff_train_y = np.log1p(dff_train_y)
dff_test = dff[1458:].drop(['GarageCars','GarageArea', 'SalePrice','YearRemodAdd','YearBuilt', 'WoodDeckSF','OpenPorchSF','EnclosedPorch','3SsnPorch','ScreenPorch'], axis =1)
dff_test.head()

Empty DataFrame
Columns: [Id, LotFrontage, LotArea, Street, Alley, LotShape, Utilities, LandSlope, OverallQual, OverallCond, MasVnrArea, BsmtQual, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, TotalBsmtSF, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BedroomAbvGr, KitchenAbvGr, TotRmsAbvGrd, Functional, Fireplaces, GarageYrBlt, GarageFinish, PavedDrive, Fence, MoSold, YrSold, LocationProximity, isNew, CentralAir_0, Garage, isRemodAdd, yrsOld, RemodAddNumYrs, TotalFinBsmtSF, TotalBathsAbvGrnd, TotalBathsBsmt, GarageYrsOld, TotalPorchArea, HeatingQuality, ExterQuality, KitchenQuality, PoolQuality, BsmtCondition, BsmtExposureMapped, GarageCondition, MSZoning_C (all), MSZoning_FV, MSZoning_RH, MSZoning_RL, MSZoning_RM, LandContour_Bnk, LandContour_HLS, LandContour_Low, LandContour_Lvl, LotConfig_Corner, LotConfig_CulDSac, LotConfig_FR2, LotConfig_FR3, LotConfig_Inside, Neighborhood_Blmngtn, Neighborhood_Blueste, Neighborhood_BrDale, Neighborhood_BrkSide, Neighborhood_ClearCr, Neighborhood_CollgCr, Neighborhood_Crawfor, Neighborhood_Edwards, Neighborhood_Gilbert, Neighborhood_IDOTRR, Neighborhood_MeadowV, Neighborhood_Mitchel, Neighborhood_NAmes, Neighborhood_NPkVill, Neighborhood_NWAmes, Neighborhood_NoRidge, Neighborhood_NridgHt, Neighborhood_OldTown, Neighborhood_SWISU, Neighborhood_Sawyer, Neighborhood_SawyerW, Neighborhood_Somerst, Neighborhood_StoneBr, Neighborhood_Timber, Neighborhood_Veenker, Condition1_Artery, Condition1_Feedr, Condition1_Norm, Condition1_PosA, Condition1_PosN, Condition1_RRAe, Condition1_RRAn, Condition1_RRNe, Condition1_RRNn, ...]
Index: []

[0 rows x 255 columns]

In [843]:
from sklearn.model_selection import train_test_split
dff_train = dff.drop(['GarageCars','GarageArea', 'Id', 'SalePrice','YearRemodAdd','YearBuilt', 'WoodDeckSF','OpenPorchSF','EnclosedPorch','3SsnPorch','ScreenPorch'], axis =1)
X_train, X_test, y_train, y_test = train_test_split(dff_train, dff['SalePrice'], test_size=0.3, random_state=101)
y_train = np.log1p(y_train)

In [844]:
from xgboost.sklearn import XGBRegressor
from sklearn.metrics import mean_squared_log_error
from math import sqrt
xgb = XGBRegressor(
       colsample_bytree=0.99929751802600186,
       
       min_child_weight=0.82986397653216548,
       n_estimators=300, nthread=-1, objective='reg:linear', reg_lambda=1, scale_pos_weight=1,
       seed=0, silent=True, subsample=0.86074883449537232)

bst = xgb.fit(X_train,y_train)
preds = xgb.predict(X_test)
preds = np.expm1(preds)
rmse = sqrt(mean_squared_log_error(y_test, preds))
rmse

0.1194233336288563

In [528]:
from xgboost.sklearn import XGBRegressor
from sklearn.metrics import mean_squared_log_error
from math import sqrt
xgb = XGBRegressor(
       colsample_bytree=0.99929751802600186,
       
       min_child_weight=0.82986397653216548,
       n_estimators=300, nthread=-1, objective='reg:linear', reg_lambda=1, scale_pos_weight=1,
       seed=0, silent=True, subsample=0.86074883449537232)

bst = xgb.fit(X_train,y_train)
preds = xgb.predict(X_test)
preds = np.expm1(preds)
rmse = sqrt(mean_squared_log_error(y_test, preds))
rmse

0.11969034365625676

In [364]:
from sklearn.model_selection import GridSearchCV
n_estimators = [350,300,400,375,325,425]
learning_rate = [0.0001, 0.001, 0.01, 0.1]
max_depth = [3, 4, 5,6,7,8]

param_grid = dict(n_estimators=n_estimators)
grid_search = GridSearchCV(xgb, param_grid,cv=5, n_jobs=-1, scoring='neg_mean_squared_log_error')
grid_result = grid_search.fit(dff_train,dff['SalePrice'])

ValueError: Parameter values for parameter (gamma) need to be a sequence(but not a string) or np.ndarray.

In [489]:
from sklearn.model_selection import RandomizedSearchCV
one_to_left = st.beta(10, 1)  
from_zero_positive = st.expon(0, 50)
params = {  
    "colsample_bytree": one_to_left,
    "subsample": one_to_left,
    "gamma": st.uniform(0, 10),
    'reg_alpha': from_zero_positive,
    "min_child_weight": from_zero_positive,
}

gs = RandomizedSearchCV(xgb, params,cv=5, n_jobs=-1, scoring='neg_mean_squared_log_error')  
gs.fit(dff_train,dff['SalePrice']) 
gs.best_params_


{'colsample_bytree': 0.99929751802600186,
 'gamma': 1.1474107529890476,
 'min_child_weight': 0.82986397653216548,
 'reg_alpha': 92.332068571277986,
 'subsample': 0.86074883449537232}

In [490]:
gs.best_estimator_

XGBRegressor(base_score=0.5, colsample_bylevel=1,
       colsample_bytree=0.99929751802600186, gamma=1.1474107529890476,
       learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=0.82986397653216548, missing=None,
       n_estimators=300, nthread=-1, objective='reg:linear',
       reg_alpha=92.332068571277986, reg_lambda=1, scale_pos_weight=1,
       seed=0, silent=True, subsample=0.86074883449537232)

In [670]:
xgb = XGBRegressor(max_depth=3, n_estimators=300, gamma = 0)
bst = xgb.fit(X_train,y_train)
preds = xgb.predict(X_test)
preds = np.expm1(preds)
rmse = sqrt(mean_squared_log_error(y_test, preds))
rmse

0.12286441169429842

In [225]:
grid_result.best_params_

{'n_estimators': 300}

In [697]:
from xgboost.sklearn import XGBRegressor

xgb = XGBRegressor(colsample_bytree=0.99929751802600186,
       min_child_weight=0.82986397653216548,
       n_estimators=300, nthread=-1, objective='reg:linear', reg_lambda=1, scale_pos_weight=1,
       seed=0, silent=True, subsample=0.86074883449537232)
bst = xgb.fit(dff_train,dff_train_y)
preds = xgb.predict(dff_test)
preds = np.expm1(preds)

In [698]:
x = {
        "Id": dff[1458:]["Id"],
        "SalePrice": preds
    }

In [699]:
submission = pd.DataFrame(x)

In [700]:
submission.to_csv('sub.csv', header=['Id','SalePrice'],index=False)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from collections import Counter
rf = RandomForestRegressor(random_state=101)
rf.fit(X_train,y_train)
scores =sorted(list(zip(map(lambda x: round(x, 4), rf.feature_importances_),X_train.columns)),reverse=True)
c =Counter([y.partition('_')[0] for (x,y) in scores])
c['Heating']

In [ ]:
import operator
def getscores(scores):
    score = dict()
    for row in scores:
        name = row[1]
        name = name.partition('_')[0]
        if name in score.keys():
            score[name]=score[name]+row[0]
        else:
            score[name]=row[0]
    
    for k, v in score.items():
        score[k]=score[k]/c[k]
    sorted_x = sorted(score.items(), key=operator.itemgetter(1),reverse=True)
    return sorted_x
x = getscores(scores)            
print(type(x))

In [ ]:
submission.to_csv('sub.csv', header=['Id','SalePrice'])

In [ ]:
from sklearn.metrics import mean_squared_log_error
from math import sqrt
pred = rf.predict(X_test)
pred = np.expm1(pred)
rmse = sqrt(mean_squared_log_error(y_test, pred))
rmse

In [ ]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression
selectkbest = SelectKBest(score_func=f_regression, k='all')
fit = selectkbest.fit(X_train, y_train)
scores_kbest =sorted(list(zip(map(lambda x: round(x, 4), fit.scores_),X_train.columns)),reverse=True)
scores_kbest_n = getscores(scores_kbest)
scores_kbest_n

In [ ]:
from sklearn.preprocessing import Normalizer
normalizer  = Normalizer().fit(df[cols_normalize])
dff_n = df.copy()
dff_n[cols_normalize.difference(['Id','SalePrice'])] = pd.DataFrame(normalizer.transform(df[cols_normalize].drop(['Id','SalePrice'], axis =1)), columns= cols_normalize.difference(['Id','SalePrice']))
#dff_n = pd.concat(dff_n.append(SalePrice)
#dff_n[['Id','SalePrice']].merge(SalePrice)
dff_n[['Id','SalePrice']] = SalePrice
dff_n.head()